name: CI/CD Pipeline  

on:  
  push:  
    branches: [ main, todo ]  # ✅ Trigger pipeline for both branches  

jobs:  
  build-and-deploy:  
    runs-on: self-hosted  # ✅ Use local GitHub Actions runner  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v3  

      - name: Build and Push Docker Image  
        run: |
          docker build -t flask-todo-app:latest .
          docker tag flask-todo-app:latest ${{ secrets.DOCKER_USERNAME }}/flask-todo-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-todo-app:latest

      - name: Start Minikube  
        run: minikube start --driver=docker  

      - name: Set Minikube to Use Local Docker  
        run: eval $(minikube -p minikube docker-env)

      - name: Deploy to Minikube  
        run: |
          kubectl delete deployment flask-todo-app --ignore-not-found=true  # Delete old deployment  
          kubectl apply -f k8s/deployment.yaml  
          kubectl apply -f k8s/service.yaml  

      - name: Verify Deployment  
        run: kubectl get pods

  


